# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    python: "git://github.com/voxpupuli/puppet-python.git"
    epel: "git://github.com/stahnma/puppet-module-epel.git"
